[email]

# Email address used as the sender.
sender = hpc_support@xxxx.edu

# Optional comma-separated CC addresses.
# Leave empty to disable CC.
cc =

# Optional comma-separated BCC addresses.
# Leave empty to disable BCC.
bcc = feng@xxx.edu

# Email subject.
subject = Summary report of your computing jobs performance on the HPC Cluster

